import type { Metadata } from 'next';
import { DM_Sans, Inter, Playfair_Display } from 'next/font/google';
import './globals.css';
import '@styles/theme.css';
import LC from './layout.c';

const dmSans = DM_Sans({
  variable: '--font-body',
  subsets: ['latin'],
});

const playfairDisplay = Playfair_Display({
  variable: '--font-heading',
  subsets: ['latin'],
});

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dmSans.variable} ${playfairDisplay.variable} ${inter.className}`}>
      <LC>
        <body>{children}</body>
      </LC>
    </html>
  );
}
